# Generated by Django 3.2.5 on 2022-03-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0004_blog_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-pulish_date']},
        ),
    ]
