# Generated by Django 3.2.5 on 2022-03-30 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0006_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-update_date']},
        ),
    ]
