# Generated by Django 3.2.5 on 2022-03-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token_for_reset_password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
