# Generated by Django 3.2.5 on 2022-04-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0003_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.FileField(blank=True, upload_to='profile_pics'),
        ),
    ]
